// Holds data for the main script to use.

export const data = {
    customWords: [
        "above", "below", "find", "hold", "drop", "stand", "move", "grow", "jump", "fast",
    "quiet", "loud", "walk", "run", "sit", "talk", "teach", "listen", "build", "fall",
    "laugh", "cry", "send", "receive", "bring", "take", "open", "close", "start", "finish",
    "hope", "dream", "read", "write", "stop", "go", "drive", "ride", "draw", "paint",
    "blue", "green", "yellow", "red", "white", "black", "big", "small", "tall", "short",
    "hot", "cold", "warm", "cool", "fast", "slow", "hard", "soft", "light", "dark",
    "high", "low", "near", "far", "left", "right", "easy", "tough", "long", "quick",
    "start", "stop", "rest", "work", "play", "learn", "help", "carry", "push", "pull",
    "city", "town", "village", "park", "home", "school", "shop", "store", "market", "bank",
    "house", "room", "street", "road", "river", "lake", "mountain", "hill", "forest", "garden",
    "car", "truck", "bus", "train", "plane", "boat", "bike", "walk", "run", "drive",
    "call", "answer", "ask", "tell", "show", "hide", "give", "receive", "send", "deliver",
    "eat", "drink", "cook", "clean", "watch", "see", "hear", "feel", "smell", "taste",
    "time", "day", "night", "week", "month", "year", "hour", "minute", "second", "moment",
    "summer", "winter", "spring", "fall", "wind", "rain", "snow", "sun", "cloud", "sky",
    "friend", "family", "teacher", "student", "child", "parent", "brother", "sister", "man", "woman",
    "dog", "cat", "bird", "fish", "horse", "cow", "sheep", "goat", "pig", "rabbit",
    "computer", "phone", "watch", "clock", "book", "pencil", "pen", "bag", "chair", "table"
        ],

        quotes: [
            "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Believe you can and you're halfway there.",
    "The way to get started is to quit talking and begin doing.",
    "Your time is limited, so don't waste it living someone else's life.",
    "The purpose of our lives is to be happy.",
    "Life is what happens when you're busy making other plans.",
    "Get busy living or get busy dying.",
    "You only live once, but if you do it right, once is enough.",
    "In three words I can sum up everything I've learned about life: It goes on.",
    "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "The mind is everything. What you think you become.",
    "The best way to predict your future is to create it.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Dream big and dare to fail.",
    "Believe in yourself and all that you are.",
    "Act as if what you do makes a difference. It does.",
    "The only way to do great work is to love what you do.",
    "Change your thoughts and you change your world.",
    "The only person you are destined to become is the person you decide to be.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "Do not wait for the perfect moment, take the moment and make it perfect.",
    "Hard times don’t create heroes. It is during the hard times when the 'hero' within us is revealed.",
    "If you want to achieve greatness stop asking for permission.",
    "To live a creative life, we must lose our fear of being wrong.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Opportunities don't happen, you create them.",
    "The starting point of all achievement is desire.",
    "Don't be afraid to give up the good to go for the great.",
    "I find that the harder I work, the more luck I seem to have.",
    "Try not to become a person of success, but rather try to become a person of value.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The way to get started is to quit talking and begin doing.",
    "Don't let yesterday take up too much of today.",
    "People who are crazy enough to think they can change the world are the ones who do.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Creativity is intelligence having fun.",
    "Do what you can with all you have, wherever you are.",
    "The question isn't who is going to let me; it's who is going to stop me.",
    "Your imagination is your preview of life's coming attractions.",
    "Setting goals is the first step in turning the invisible into the visible.",
    "All our dreams can come true, if we have the courage to pursue them.",
    "The only thing standing between you and your goal is the story you keep telling yourself.",
    "I never dreamed about success, I worked for it.",
    "Do one thing every day that scares you.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Don’t wish it were easier, wish you were better.",
    "Do not wait to strike till the iron is hot; but make it hot by striking.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The harder I practice, the luckier I get.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Don’t watch the clock; do what it does. Keep going.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
    "Don’t count the days, make the days count.",
    "If you want to fly, you have to give up the things that weigh you down.",
    "Happiness is not something ready made. It comes from your own actions.",
    "A goal is not always meant to be reached, it often serves simply as something to aim at.",
    "Failure is not the opposite of success; it's part of success.",
    "You don't need to see the whole staircase, just take the first step.",
    "The best revenge is massive success.",
    "You miss 100% of the shots you don’t take.",
    "It’s not whether you get knocked down, it’s whether you get up.",
    "Your limitation—it’s only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Don’t stop until you’re proud.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Wake up with determination. Go to bed with satisfaction.",
    "It’s not about having time. It’s about making time.",
    "To see what is right and not do it is a lack of courage.",
    "Do what is right, not what is easy.",
    "Believe in your infinite potential. Your only limitations are those you set upon yourself.",
    "The secret to getting ahead is getting started.",
    "All our dreams can come true if we have the courage to pursue them.",
    "The only place where success comes before work is in the dictionary.",
    "Don’t let yesterday take up too much of today.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Success is a journey, not a destination.",
    "You can’t use up creativity. The more you use, the more you have.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit."
        ],
};